Repository yiisoft/docs, pull requests merged in 2023-03, with the labels that each got.

#135 Add style linter
  .github/styles/.gitkeep
  .github/workflows/docs.yml
  .vale.ini
  014-docs.md
Labels: type:feature

#61 add indonesian translation guide
  guide/id/README.md
Labels: status:under development, translation

#49 [WIP] Spanish Translation
  guide/es/README.md
  guide/es/concept/aliases.md
  guide/es/concept/autoloading.md
  guide/es/concept/configuration.md
  guide/es/concept/di-container.md
  guide/es/concept/events.md
  guide/es/intro/upgrade-from-v2.md
  guide/es/intro/what-is-yii.md
  guide/es/runtime/cookies.md
  guide/es/runtime/flash-messages.md
  guide/es/runtime/handling-errors.md
  guide/es/runtime/logging.md
  guide/es/runtime/request.md
  guide/es/runtime/response.md
  guide/es/runtime/sessions.md
  guide/es/security/authentication.md
  guide/es/security/authorization.md
  guide/es/security/best-practices.md
  guide/es/security/cryptography.md
  guide/es/security/img/rbac-access-check-1.graphml
  guide/es/security/img/rbac-access-check-1.svg
  guide/es/security/img/rbac-access-check-2.graphml
  guide/es/security/img/rbac-access-check-2.svg
  guide/es/security/img/rbac-access-check-3.graphml
  guide/es/security/img/rbac-access-check-3.svg
  guide/es/security/img/rbac-hierarchy-1.graphml
  guide/es/security/img/rbac-hierarchy-1.svg
  guide/es/security/img/rbac-hierarchy-2.graphml
  guide/es/security/img/rbac-hierarchy-2.svg
  guide/es/security/overview.md
  guide/es/security/passwords.md
  guide/es/security/trusted-request.md
  guide/es/start/databases.md
  guide/es/start/forms.md
  guide/es/start/gii.md
  guide/es/start/hello.md
  guide/es/start/installation.md
  guide/es/start/looking-ahead.md
  guide/es/start/prerequisites.md
  guide/es/start/workflow.md
  guide/es/structure/action.md
  guide/es/structure/application.md
  guide/es/structure/domain.md
  guide/es/structure/entry-script.md
  guide/es/structure/handler.md
  guide/es/structure/img/middleware.graphml
  guide/es/structure/img/middleware.svg
  guide/es/structure/middleware.md
  guide/es/structure/overview.md
  guide/es/structure/package.md
  guide/es/structure/service.md
  guide/es/tutorial/console-applications.md
  guide/es/tutorial/performance-tuning.md
  guide/es/tutorial/using-with-event-loop.md
  guide/es/tutorial/using-yii-with-roadrunner.md
  guide/es/tutorial/using-yii-with-swoole.md
Labels: translation
